DROP TABLE RANKINGBOARD;
DROP TABLE UPLOAD;
DROP TABLE NOTICEBOARD;
DROP TABLE REVIEWBOARD;
DROP TABLE SUYO;
DROP TABLE DIET;
DROP TABLE DSURVEY;
DROP TABLE COUNTER;
DROP TABLE EVENT;
DROP TABLE ALRAM;
DROP TABLE REVIEW;
DROP TABLE FOODMENU;
DROP TABLE SCHEDULE;
DROP TABLE ANOBOARD;
DROP TABLE PSURVEY;
DROP TABLE FOOD;
DROP TABLE MEMBER;

DROP SEQUENCE ANOBOARD_NO;
DROP SEQUENCE ANOBOARD_PW;
DROP SEQUENCE DIET_NO;
DROP SEQUENCE DSURVEY_NO;
DROP SEQUENCE FOOD_NO;
DROP SEQUENCE FOODMENU_NO;
DROP SEQUENCE NOTICEBOARD_NO;
DROP SEQUENCE PSURVEY_NO;
DROP SEQUENCE RANKINGBOARD_NO;
DROP SEQUENCE REVIEWBOARD_NO;
DROP SEQUENCE REVIEW_NO;
DROP SEQUENCE SCHEDULE_NO;
DROP SEQUENCE UPLOAD_NO;

CREATE TABLE MEMBER(mno NUMBER PRIMARY KEY,
					grade CHAR DEFAULT 'N',
                    PASSWORD VARCHAR2(255) NOT NULL,
                    mname VARCHAR2(255) NOT NULL,
                    phone VARCHAR2(255) NOT NULL,
                    email VARCHAR2(255) NOT NULL,
                    prefer VARCHAR2(2000)
                    );
CREATE TABLE ANOBOARD(ANO NUMBER PRIMARY KEY,
					 ANOPW VARCHAR2(255) NOT NULL,
                     ANOTITLE VARCHAR2(255) NOT NULL,
                     ANOCONTENTS VARCHAR2(2000),
                     ANODATE DATE
                     );
CREATE TABLE SCHEDULE(scode NUMBER PRIMARY KEY,
					 sname VARCHAR2(255) NOT NULL
                     );
CREATE TABLE DIET(DIETNO NUMBER PRIMARY KEY,
				  SCODE NUMBER REFERENCES SCHEDULE(SCODE),
                  DIETDATE DATE,
                  MAINDISH VARCHAR2(50) NOT NULL,
                  SIDEDISH VARCHAR2(2000)
                  );
CREATE TABLE SUYO(DIETNO NUMBER REFERENCES DIET(DIETNO),
				  MNO NUMBER REFERENCES MEMBER(MNO)
                  );

CREATE TABLE REVIEWBOARD(RNO NUMBER PRIMARY KEY,
						 MNO NUMBER REFERENCES MEMBER(MNO),
                         SPOINT NUMBER DEFAULT 0,
                         COMMENTS VARCHAR2(2000),
                         SCODE NUMBER REFERENCES SCHEDULE(SCODE),
                         FNAME VARCHAR2(50) NOT NULL,
                         REGDATE DATE
                         );
CREATE TABLE NOTICEBOARD(NNO NUMBER PRIMARY KEY,
						 MNO NUMBER REFERENCES MEMBER(MNO),
                         TITLE VARCHAR2(255) NOT NULL,
                         CONTENTS VARCHAR2(2000),
                         NDATE DATE
                         );
CREATE TABLE RANKINGBOARD(RKNO NUMBER PRIMARY KEY,
						  RKNAME VARCHAR2(255) NOT NULL,
                          IMG VARCHAR2(255) NOT NULL,
                          REGDATE DATE,
                          SCODE NUMBER REFERENCES SCHEDULE(SCODE)
                          );
CREATE TABLE COUNTER(CDATE DATE NOT NULL,
					 MCNT NUMBER DEFAULT 0,
                     ICNT NUMBER DEFAULT 0,
                     HCNT NUMBER DEFAULT 0,
                     ECNT NUMBER DEFAULT 0
                     );
CREATE TABLE EVENT(EDATE DATE NOT NULL,
					MNO NUMBER REFERENCES MEMBER(MNO)
                    );

CREATE SEQUENCE ANOBOARD_NO;
CREATE SEQUENCE DIET_NO;
CREATE SEQUENCE NOTICEBOARD_NO;
CREATE SEQUENCE RANKINGBOARD_NO;
CREATE SEQUENCE REVIEWBOARD_NO;
CREATE SEQUENCE ANOBOARD_PW;

COMMIT;



